<?php

namespace TodoListBundle\Repository;
use TodoListBundle\Entity\Event;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{


    public function findAllEventedByType($type)
    {
        $qb = $this->createQueryBuilder('e')
            ->Where('e.type = :type')
            ->setParameter('type', $type)
            ->getQuery();

        return $qb->execute();
    }
}
